### ISSUE TITLE
make it easy to share current map position

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim-Data-Analyser#2]
Osmoscope adds URL fragments with current map position and zoom whenever one moves the map, e.g. `#map=17.991666666666667/6.8867/52.24745` This makes it easy to share the current view with other users.

**Comment by AntoJvlt** [comment]
Transferred this issue to the new repository: https://github.com/osm-search/Nominatim-Data-Analyser-Frontend/issues/1#issue-974017892.
