### ISSUE TITLE
Add "address far away from its road"

### ISSUE THREAD

**Issue by matkoniecz** [osm-search/Nominatim-Data-Analyser#29]
It often indicates address problems, road data problems or both.

https://wiki.openstreetmap.org/wiki/Mr%C3%B3wki runs such QA server for Poland and it was/is very useful.

pink: 150m - 1500m from road to address
yellow: over 1500m from road to address

**Comment by lonvia** [comment]
You get the ones that are too far away in the layer "addr:street wrong name" because the radius in which Nominatim searches a street is restricted.
