### ISSUE TITLE
Use service roads to help determine the "right" road for an address

### ISSUE THREAD

**Issue by tsmock** [osm-search/Nominatim-Data-Analyser#30]
Example: https://www.openstreetmap.org/way/497029571
https://nominatim.org/qa/#map=16.90/39.10/-108.42&layer=addr_street_wrong_name

In this instance, the address is wrongly detected as belonging to 34 1/4 Road, when it properly belongs with 34 Road. The building with the address has a service road (`highway=service` `service=driveway`) leading from the proper road to the building.

**Comment by lonvia** [comment]
This was an issue with partial name matching in Nominatim that has been fixed in the meantime. See https://github.com/osm-search/Nominatim/issues/2534 for the original report. 

Addresses will sort themselves out only gradually as new updates come in.
