### ISSUE TITLE
take layer information into account on addr:streename check?

### ISSUE THREAD

**Issue by hartmut-mariadb** [osm-search/Nominatim-Data-Analyser#31]
I'm getting a false positive here, saying that the nodes streetname "Jahnplatz" conflicts with the parent "Jahnplatz (U)"

The node is on the buildings ground floor over ground, while "Jahnplatz (U)" is actually at layer=-2 underground (and wrongly labeled as "raiyway=platform" and "highway=footpath"):

https://nominatim.org/qa/#map=21.03/52.02/8.53&layer=addr_street_wrong_name

Node is: https://www.openstreetmap.org/node/5139522754

Platform way is: https://www.openstreetmap.org/way/260631154

It's probably a rare situation to have overlapping streets at different levels, and in this specific case the tagging is also questionable, but it may make sense to prioritize streets on the same level as the object tagged with addr:street in this check?

**Comment by lonvia** [comment]
I'd rather file that as a data error. Nominatim does not look at level information and I think it is a rather healthy goal to strive for data that is possible to process without such detailed knowledge.

You can change `highway=footpath` to `highway=platform` to indicate the special nature of the way. I've recently changed Nominatim to put those in the same category as all other PT stops.

**Comment by hartmut-mariadb** [comment]
Yes, this specific case is rather clearly a data error. Trying to think of any valid case of overlapping (not just crossing) at different levels,  in theory it could have hit at this situation here with "Ostwestfalendamm" being above "Mindener Straße", and closer to the houses on the west side. 

But in reality neither "Mindener Straße" nor "Ostwestfalendamm" have any buildings with that street address, all the nearby buildings are associated with other roads nearby. 

It's probably rare enough to simply ignore the few true false positives that may arise due to such two level road situations, if there are any at all.

(Now I just need to remember to change github accounts before filing non-work-related reports ... :o

**Comment by lonvia** [comment]
Remember that Nominatim matches by the name in addr:street. So for this to really be an issue, you'd need to have overlapping ways with the same name. And that situations probably brings a whole bag of other problems.
