### ISSUE TITLE
can't see last update info for some layers

### ISSUE THREAD

**Issue by joshinils** [osm-search/Nominatim-Data-Analyser#38]
related: #17

![image](https://user-images.githubusercontent.com/34302971/155717126-bc8cad9a-c5fb-4a30-bab3-ef474f97fa32.png)
the html data is there, the `max-height: 500px` is just too small to show it at the bottom

**Comment by lonvia** [comment]
Already mentioned in https://github.com/osm-search/Nominatim-Data-Analyser-Frontend/pull/34 but probably better as its own issue.

**Comment by AntoJvlt** [comment]
Solved in https://github.com/osm-search/Nominatim-Data-Analyser-Frontend/pull/38
