### ISSUE TITLE
False-positive for neighbouring place=square

### ISSUE THREAD

**Issue by joshinils** [osm-search/Nominatim-Data-Analyser#39]
https://www.openstreetmap.org/node/9122275031
is next to the Otto-Weidt-Platz:
https://www.openstreetmap.org/way/642581102

**Comment by joshinils** [comment]
same with a neighbouring `leisure=park`
park: https://www.openstreetmap.org/way/25950008
thing inside that park: https://www.openstreetmap.org/way/236632861

**Comment by joshinils** [comment]
same with a `man_made=bridge`
bridge: https://www.openstreetmap.org/way/659061378
restaurant: https://www.openstreetmap.org/node/272820430

**Comment by lonvia** [comment]
The first two need an `addr:place` instead of `addr:street`.

The third has the wrong address. It is "Vor dem Schlesischen Tor 2 " according to the website of the restaurant.

**Comment by joshinils** [comment]
thank you, did not think of `addr:place` i will edit those and other occurrences next to other places and parks i have seen since

**Comment by joshinils** [comment]
I guess that's on me for not reading the whole description for the layer. 
though it would be possible to show that a nearby park or place has the same name to hint for this `addr:street` -> `addr:place` issue.

**Comment by lonvia** [comment]
That would be too expensive to compute.

Closing as data issue.
