### ISSUE TITLE
Suspicious addr:street tag turns up results which aren't present on linked OSM object

### ISSUE THREAD

**Issue by pnorman** [osm-search/Nominatim-Data-Analyser#42]
https://nominatim.org/qa/#map=18.16/49.32/-123.14&layer=addr_street_wrong_name turns up a bunch of errors, for example one with [this node](https://www.openstreetmap.org/node/6434862028)

It claims "street_name: Park Royal S" and "parent_name: Park Royal South". Assuming that addr:street is the street_name, it is not set on the way, and the tagging has not changed recently.

addr:street was present on an [enclosing way](https://www.openstreetmap.org/way/42277873) that was not in the area I initially downloaded.

The instructions make no mention of addr:street tags on different objects.

**Comment by lonvia** [comment]
This is odd. 45eec194c3186c3e603f9ed133fa3990ba659f2e should have fixed that.

**Comment by lonvia** [comment]
Wrong rule. I've now excluded inherited addresses in all address-related checks. You will see the effects tomorrow morning (UTC).

**Comment by pnorman** [comment]
Looks to be working.
