### ISSUE TITLE
False negatives in "Suspicious addr:street tag"

### ISSUE THREAD

**Issue by osmuser63783** [osm-search/Nominatim-Data-Analyser#45]
The "Suspicious addr:street tag" layer is missing quite a few nodes that Nominatim assigns a street with a name different from the value of their addr:street tag, because the value isn't in the `name` field of any nearby `highway` objects.

Some example nodes
* https://www.openstreetmap.org/node/2920296590
* https://www.openstreetmap.org/node/2867498074

The street names *are* recorded in `name:left` or `name:right` of the highway objects ([example](https://www.openstreetmap.org/way/385197914)), but I thought Nominatim ignores those tags? Since these nodes don't work correctly in Nominatim (it assigns the correct street but then shows the address as 21 Leith Walk, see [here](https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=2920296909&class=place)), it's odd that the QA tool doesn't flag them.

**Comment by lonvia** [comment]
It is not flagged because the tagging is in principle correct. It did find a street with the name as in `addr:street` and made that the parent street. It is also possible to search the address. (Note that any of the street's  `name:*` matching the `addr:street` tag is considered fine, there are valid cases for it) The display name being off is just an unimplemented feature of Nominatim but not an issue with the tagging. 

That said, I'd rather remove the `name:left` from the street here and change in the address node `addr:street` to `addr:place`. You should also have a look at https://wiki.openstreetmap.org/wiki/Addresses_in_the_United_Kingdom

**Comment by osmuser63783** [comment]
I see, thanks for looking at this! Yes, we're [discussing](https://www.openstreetmap.org/note/3087279) the best way to solve this problem and I stumbled upon addr:place as a possible solution.

It's not just that the display name from Nominatim is wrong, we actually get some incorrect matches. For example [this query](https://nominatim.openstreetmap.org/ui/search.html?q=7+leith+walk) returns multiple incorrect results before the correct one.

What I've found so far is that just replacing addr:street with addr:place isn't enough ([example](https://nominatim.openstreetmap.org/ui/search.html?q=1+royal+terrace+gardens)), it seems like you also need to create a [place](https://www.openstreetmap.org/relation/15867809) to get [correct results](https://nominatim.openstreetmap.org/ui/search.html?q=1+leopold+place).

I'm trying to find out how many such places we would need to re-tag this way and this is how I stumbled upon this QA tool!

**Comment by lonvia** [comment]
> What I've found so far is that just replacing addr:street with addr:place isn't enough it seems like you also need to create a place to get correct results.

No, you don't.

**Comment by osmuser63783** [comment]
Did you look at the [example](https://nominatim.openstreetmap.org/ui/search.html?q=1+royal+terrace+gardens) I posted? I'm expecting to get either [this node](https://www.openstreetmap.org/node/3287615132) or [this one](https://www.openstreetmap.org/node/10853538418), but I only get them after clicking 'search for more results' twice (i.e. excluding the top 7 results), even though it's a perfect match on the name.

I know that in principle Nominatim will find a result tagged addr:place even if there isn't a corresponding place. In practice it seems to work much better (rank much higher) if there is an object with that name.

I'm also completely unable to find [this node](https://www.openstreetmap.org/node/10226495552) through Nominatim even when I type in [the the full address](https://nominatim.openstreetmap.org/ui/search.html?q=107+St+James+Crescent+edinburgh+EH1+3AD).

Is it worth opening a ticket in the Nominatim issue tracker or am I doing something wrong?

**Comment by lonvia** [comment]
Again, this is a short-coming in the way the results are presented by Nominatim but it is not a problem with the tagging per se. Thus not a false negative in Nomiantim QA.
